# Generated by Django 3.2 on 2021-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BookName',
            field=models.CharField(default='', max_length=20, verbose_name='名称1'),
        ),
    ]
